### ISSUE TITLE
Update GCP Auth Strategy to Workload Identity Federation

### ISSUE THREAD

**Issue by SpaceKatt** [SpaceKatt/spacekatt-io#8]
Use [Workload Identity Federation](https://cloud.google.com/iam/docs/workload-identity-federation) to authenticate to GCP without a secret.

```yaml
     - id: auth
       uses: google-github-actions/auth@v0.4.0
       with:
         workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
         service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }
```

Current auth strategy has been deprecated:

```txt
Warning: "service_account_key" has been deprecated. Please switch to using google-github-actions/auth which supports both Workload Identity Federation and Service Account Key JSON authentication. For more details, see https://github.com/google-github-actions/setup-gcloud#authorization
```
